"""
Finance MART 2 end-to-end smoke test for 2028 data.

What it does:
  1) Inserts a small deterministic 2028 test dataset into Source_FinanceOps_DB.finance_ops.
  2) Runs Source -> Staging ETL.
  3) Runs DW first-load ETL for Jan/Feb 2028.
  4) Verifies staging validity, dimensions, transaction facts, monthly snapshot, lifecycle.
  5) Applies incremental source changes/inserts for March 2028.
  6) Runs Source -> Staging again and DW normal/daily ETL.
  7) Verifies incremental dimension updates and March fact/snapshot rows.

Assumptions:
  - Your DB objects and ETL procedures already exist.
  - For a clean comprehensive test, run this on an empty/test database or with the 2028 range unused.
  - The script uses fixed high IDs starting at TEST_ID_BASE so it does not collide with normal seed data.

Required package:
  pip install pyodbc
"""

from __future__ import annotations

import sys
from datetime import date, datetime
from decimal import Decimal
from typing import Any, Iterable

try:
    import pyodbc
except ImportError:
    print("Missing package: pyodbc. Install with: pip install pyodbc")
    raise

# =============================================================================
# Configuration
# =============================================================================

DRIVER = "ODBC Driver 18 for SQL Server"
SERVER = r"localhost"              # Example: r"GOD-PC" or r"GOD-PC\SQLEXPRESS"
TRUSTED_CONNECTION = True            # True = Windows Auth. False = SQL Auth.
SQL_USER = "sa"
SQL_PASSWORD = "YourStrongPassword"
TRUST_SERVER_CERTIFICATE = True

SOURCE_DB = "Source_FinanceOps_DB"
STG_DB = "Stg_FinanceOps_DB"
DW_DB = "Charity_DW_DB"

# Fixed high IDs used only by this smoke test.
TEST_ID_BASE = 2_028_000

# Keep this False by default. True deletes only previous rows generated by this script.
CLEAN_PREVIOUS_TEST_ROWS = True

# If dim_center / dim_child do not exist, this creates minimal test versions.
# If your real MART 1 already exists, keep True; it will only insert missing center_id/child_id rows.
ENSURE_MINIMAL_CONFORMED_DIMS = True

# If True, script stops on the first failed verification.
STOP_ON_FIRST_FAILURE = False

# Test period boundaries.
FIRST_LOAD_START = "2028-01-01T00:00:00"
FIRST_LOAD_END = "2028-03-01T00:00:00"       # Jan + Feb only
INCREMENTAL_START = "2028-03-01T00:00:00"
INCREMENTAL_END = "2028-04-01T00:00:00"      # Mar only
DIM_DATE_START = "2028-01-01"
DIM_DATE_END = "2028-04-30"


# =============================================================================
# Connection and helpers
# =============================================================================


def connect() -> pyodbc.Connection:
    if TRUSTED_CONNECTION:
        conn_str = (
            f"DRIVER={{{DRIVER}}};"
            f"SERVER={SERVER};"
            "Trusted_Connection=yes;"
            f"TrustServerCertificate={'yes' if TRUST_SERVER_CERTIFICATE else 'no'};"
        )
    else:
        conn_str = (
            f"DRIVER={{{DRIVER}}};"
            f"SERVER={SERVER};"
            f"UID={SQL_USER};PWD={SQL_PASSWORD};"
            f"TrustServerCertificate={'yes' if TRUST_SERVER_CERTIFICATE else 'no'};"
        )
    conn = pyodbc.connect(conn_str)
    conn.autocommit = False
    return conn


def exec_sql(conn: pyodbc.Connection, sql: str, params: Iterable[Any] | None = None) -> None:
    cur = conn.cursor()
    cur.execute(sql, tuple(params or ()))
    cur.close()


def fetch_all(conn: pyodbc.Connection, sql: str, params: Iterable[Any] | None = None) -> list[pyodbc.Row]:
    cur = conn.cursor()
    cur.execute(sql, tuple(params or ()))
    rows = cur.fetchall()
    cur.close()
    return rows


def fetch_one(conn: pyodbc.Connection, sql: str, params: Iterable[Any] | None = None) -> pyodbc.Row | None:
    cur = conn.cursor()
    cur.execute(sql, tuple(params or ()))
    row = cur.fetchone()
    cur.close()
    return row


def scalar(conn: pyodbc.Connection, sql: str, params: Iterable[Any] | None = None) -> Any:
    row = fetch_one(conn, sql, params)
    if row is None:
        return None
    return row[0]


def table_exists(conn: pyodbc.Connection, three_part_name: str) -> bool:
    return bool(scalar(conn, "SELECT CASE WHEN OBJECT_ID(?, 'U') IS NULL THEN 0 ELSE 1 END", [three_part_name]))


def col_exists(conn: pyodbc.Connection, table_name: str, column_name: str) -> bool:
    return scalar(conn, "SELECT CASE WHEN COL_LENGTH(?, ?) IS NULL THEN 0 ELSE 1 END", [table_name, column_name]) == 1


def begin_identity_insert(conn: pyodbc.Connection, table: str) -> None:
    exec_sql(conn, f"SET IDENTITY_INSERT {table} ON;")


def end_identity_insert(conn: pyodbc.Connection, table: str) -> None:
    exec_sql(conn, f"SET IDENTITY_INSERT {table} OFF;")


def normalize_param(column_name: str, value: Any) -> Any:
    """Convert Python-side values to types that SQL Server ODBC casts safely."""
    if value is None:
        return None

    lower_col = column_name.lower()

    # Keep BIT columns explicit.
    if lower_col in {"is_active", "is_valid", "is_confirmed", "is_refunded"}:
        return int(value)

    # DATE-only source columns.
    date_only_cols = {
        "start_date",
        "end_date",
        "donation_date",
        "expense_date",
        "payment_date",
        "allocation_date",
        "transaction_date",
        "rate_date",
    }
    if lower_col in date_only_cols and isinstance(value, str):
        return date.fromisoformat(value[:10])

    # DATETIME2 source columns.
    if lower_col.endswith("_at") and isinstance(value, str):
        return datetime.fromisoformat(value.replace("Z", "+00:00")).replace(tzinfo=None)

    return value


def normalize_rows(columns: list[str], rows: list[tuple[Any, ...]]) -> list[tuple[Any, ...]]:
    return [tuple(normalize_param(col, val) for col, val in zip(columns, row)) for row in rows]


def insert_with_identity(conn: pyodbc.Connection, table: str, columns: list[str], rows: list[tuple[Any, ...]]) -> None:
    if not rows:
        return
    col_sql = ", ".join(columns)
    placeholders = ", ".join("?" for _ in columns)
    sql = f"INSERT INTO {table} ({col_sql}) VALUES ({placeholders});"
    safe_rows = normalize_rows(columns, rows)
    begin_identity_insert(conn, table)
    try:
        cur = conn.cursor()
        # For this smoke test the batches are tiny; disabling fast_executemany avoids
        # ODBC type-inference issues with mixed NULL/date/datetime parameters.
        cur.fast_executemany = False
        cur.executemany(sql, safe_rows)
        cur.close()
    finally:
        end_identity_insert(conn, table)


def assert_or_record(results: list[tuple[str, bool, str]], name: str, ok: bool, detail: str = "") -> None:
    results.append((name, ok, detail))
    mark = "PASS" if ok else "FAIL"
    print(f"[{mark}] {name}" + (f" :: {detail}" if detail else ""))
    if STOP_ON_FIRST_FAILURE and not ok:
        raise AssertionError(f"{name}: {detail}")


# =============================================================================
# Optional cleanup and conformed dimension preparation
# =============================================================================


def clean_previous_test_rows(conn: pyodbc.Connection) -> None:
    print("Cleaning previous smoke-test rows only...")

    # Source cleanup, dependency order.
    source_deletes = [
        f"DELETE FROM {SOURCE_DB}.finance_ops.financial_transactions WHERE id >= ?",
        f"DELETE FROM {SOURCE_DB}.finance_ops.budget_allocations WHERE id >= ?",
        f"DELETE FROM {SOURCE_DB}.finance_ops.payments WHERE id >= ?",
        f"DELETE FROM {SOURCE_DB}.finance_ops.expenses WHERE id >= ?",
        f"DELETE FROM {SOURCE_DB}.finance_ops.donations WHERE id >= ?",
        f"DELETE FROM {SOURCE_DB}.finance_ops.currency_rates WHERE id >= ?",
        f"DELETE FROM {SOURCE_DB}.finance_ops.expense_categories WHERE id >= ?",
        f"DELETE FROM {SOURCE_DB}.finance_ops.campaigns WHERE id >= ?",
        f"DELETE FROM {SOURCE_DB}.finance_ops.donors WHERE id >= ?",
    ]
    for sql in source_deletes:
        exec_sql(conn, sql, [TEST_ID_BASE])

    # Staging cleanup. Source-to-staging incremental procedures do not necessarily delete old staging rows.
    stg_tables = [
        "financial_transactions",
        "budget_allocations",
        "payments",
        "expenses",
        "donations",
        "currency_rates",
        "expense_categories",
        "campaigns",
        "donors",
    ]
    for tbl in stg_tables:
        full = f"{STG_DB}.stg_finance_ops.{tbl}"
        if table_exists(conn, full):
            if tbl == "financial_transactions":
                exec_sql(conn, f"DELETE FROM {full} WHERE id >= ?", [TEST_ID_BASE])
            else:
                exec_sql(conn, f"DELETE FROM {full} WHERE id >= ?", [TEST_ID_BASE])

    # DW finance fact cleanup by source IDs.
    dw_cleanup = [
        f"DELETE FROM {DW_DB}.dw.fact_budget_allocation_event WHERE source_allocation_id >= ? OR source_id >= ?",
        f"DELETE FROM {DW_DB}.dw.fact_donation_lifecycle WHERE source_donation_id >= ?",
        f"DELETE FROM {DW_DB}.dw.fact_donation_transaction WHERE source_donation_id >= ?",
        f"DELETE FROM {DW_DB}.dw.fact_expense_transaction WHERE source_expense_id >= ?",
        f"DELETE FROM {DW_DB}.dw.fact_payment_transaction WHERE source_payment_id >= ?",
        f"DELETE FROM {DW_DB}.dw.dim_donor WHERE donor_id >= ?",
        f"DELETE FROM {DW_DB}.dw.dim_campaign WHERE campaign_id >= ?",
        f"DELETE FROM {DW_DB}.dw.dim_category WHERE category_id >= ?",
    ]
    for sql in dw_cleanup:
        param_count = sql.count("?")
        exec_sql(conn, sql, [TEST_ID_BASE] * param_count)

    # Snapshot cleanup for 2028 test months. This assumes the 2028 range is reserved for this smoke test.
    if table_exists(conn, f"{DW_DB}.dw.fact_monthly_financial_snapshot"):
        exec_sql(
            conn,
            f"""
            DELETE FROM {DW_DB}.dw.fact_monthly_financial_snapshot
            WHERE month_key IN (20280131, 20280229, 20280331)
            """,
        )

    conn.commit()



def ensure_conformed_dim_table(conn: pyodbc.Connection, table: str, key_col: str, id_col: str, name_col: str) -> None:
    full = f"{DW_DB}.dw.{table}"
    if table_exists(conn, full):
        return
    if not ENSURE_MINIMAL_CONFORMED_DIMS:
        raise RuntimeError(f"Missing required conformed dimension: {full}")

    print(f"Creating minimal test-only {full} because it does not exist...")
    exec_sql(
        conn,
        f"""
        USE {DW_DB};
        IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'dw') EXEC(N'CREATE SCHEMA dw');
        CREATE TABLE dw.{table} (
            {key_col} INT IDENTITY(1,1) NOT NULL,
            {id_col} INT NULL,
            {name_col} NVARCHAR(200) NULL,
            source_system NVARCHAR(100) NULL,
            created_at DATETIME2(0) NULL,
            updated_at DATETIME2(0) NULL
        );
        """,
    )
    conn.commit()


def insert_conformed_dim_row(conn: pyodbc.Connection, table: str, id_col: str, id_value: int, values: dict[str, Any]) -> None:
    full = f"{DW_DB}.dw.{table}"
    if not table_exists(conn, full):
        raise RuntimeError(f"Missing table: {full}")
    if not col_exists(conn, full, id_col):
        raise RuntimeError(f"{full} must have column {id_col}")

    exists = scalar(conn, f"SELECT COUNT(1) FROM {full} WHERE {id_col} = ?", [id_value])
    if exists:
        return

    available_cols = [r[0] for r in fetch_all(
        conn,
        """
        SELECT c.name
        FROM ?.sys.columns c
        """.replace("?", DW_DB) + f" WHERE c.object_id = OBJECT_ID('{DW_DB}.dw.{table}')",
    )]

    insert_cols: list[str] = []
    insert_vals: list[Any] = []
    all_values = {id_col: id_value, **values}
    for col, val in all_values.items():
        if col in available_cols:
            insert_cols.append(col)
            insert_vals.append(val)

    if id_col not in insert_cols:
        raise RuntimeError(f"Cannot insert {full}; missing {id_col}")

    sql = f"INSERT INTO {full} ({', '.join(insert_cols)}) VALUES ({', '.join('?' for _ in insert_cols)});"
    exec_sql(conn, sql, insert_vals)


def ensure_conformed_dims(conn: pyodbc.Connection) -> None:
    print("Ensuring minimal dim_date, dim_center, and dim_child prerequisites...")

    # Fill dim_date for 2028.
    if table_exists(conn, f"{DW_DB}.etl_admin.usp_fill_dw_dim_date"):
        pass
    # OBJECT_ID does not check procedures with 'U', so just execute and let it fail clearly if missing.
    exec_sql(
        conn,
        f"EXEC {DW_DB}.etl_admin.usp_fill_dw_dim_date @start_date = ?, @end_date = ?;",
        [DIM_DATE_START, DIM_DATE_END],
    )

    # Minimal conformed center/child dims if MART 1 is not present.
    ensure_conformed_dim_table(conn, "dim_center", "center_key", "center_id", "center_name")
    ensure_conformed_dim_table(conn, "dim_child", "child_key", "child_id", "child_name")

    insert_conformed_dim_row(
        conn,
        "dim_center",
        "center_id",
        1,
        {
            "center_name": "Smoke Test Center 1",
            "name": "Smoke Test Center 1",
            "source_system": "PROGRAM_OPS",
            "created_at": "2028-01-01T00:00:00",
            "updated_at": None,
        },
    )
    insert_conformed_dim_row(
        conn,
        "dim_center",
        "center_id",
        2,
        {
            "center_name": "Smoke Test Center 2",
            "name": "Smoke Test Center 2",
            "source_system": "PROGRAM_OPS",
            "created_at": "2028-01-01T00:00:00",
            "updated_at": None,
        },
    )
    insert_conformed_dim_row(
        conn,
        "dim_child",
        "child_id",
        1,
        {
            "child_name": "Smoke Test Child 1",
            "full_name": "Smoke Test Child 1",
            "name": "Smoke Test Child 1",
            "source_system": "PROGRAM_OPS",
            "created_at": "2028-01-01T00:00:00",
            "updated_at": None,
        },
    )
    insert_conformed_dim_row(
        conn,
        "dim_child",
        "child_id",
        2,
        {
            "child_name": "Smoke Test Child 2",
            "full_name": "Smoke Test Child 2",
            "name": "Smoke Test Child 2",
            "source_system": "PROGRAM_OPS",
            "created_at": "2028-01-01T00:00:00",
            "updated_at": None,
        },
    )
    conn.commit()


# =============================================================================
# Source test data
# =============================================================================


def insert_first_load_source_data(conn: pyodbc.Connection) -> None:
    print("Inserting deterministic FIRST-LOAD source data for Jan/Feb 2028...")

    donor_cols = ["id", "full_name", "national_id", "phone", "email", "donor_type", "is_active", "created_at", "updated_at"]
    donors = [
        (TEST_ID_BASE + 1, "Smoke 2028 Donor A", "SMOKE-NID-2028-A", "09128000001", "smoke-a@example.com", "individual", 1, "2028-01-02T08:00:00", None),
        (TEST_ID_BASE + 2, "Smoke 2028 Donor Org B", "SMOKE-NID-2028-B", "02128000002", "smoke-b@example.com", "organization", 1, "2028-01-03T08:00:00", None),
    ]
    insert_with_identity(conn, f"{SOURCE_DB}.finance_ops.donors", donor_cols, donors)

    campaign_cols = ["id", "title", "description", "target_amount", "start_date", "end_date", "status", "created_at", "updated_at"]
    campaigns = [
        (TEST_ID_BASE + 1, "Smoke 2028 Campaign", "Smoke test campaign for ETL validation.", Decimal("100000.00"), "2028-01-01", "2028-12-31", "active", "2028-01-01T09:00:00", None),
    ]
    insert_with_identity(conn, f"{SOURCE_DB}.finance_ops.campaigns", campaign_cols, campaigns)

    category_cols = ["id", "name", "parent_id", "is_active", "created_at", "updated_at"]
    categories = [
        (TEST_ID_BASE + 1, "Smoke Education", None, 1, "2028-01-01T09:00:00", None),
        (TEST_ID_BASE + 2, "Smoke Books", TEST_ID_BASE + 1, 1, "2028-01-01T09:00:00", None),
        (TEST_ID_BASE + 3, "Smoke Meals", TEST_ID_BASE + 1, 1, "2028-01-01T09:00:00", None),
    ]
    insert_with_identity(conn, f"{SOURCE_DB}.finance_ops.expense_categories", category_cols, categories)

    donation_cols = ["id", "donor_id", "campaign_id", "amount", "currency", "donation_type", "donation_date", "status", "reference_code", "created_at", "updated_at"]
    donations = [
        (TEST_ID_BASE + 101, TEST_ID_BASE + 1, TEST_ID_BASE + 1, Decimal("1000.00"), "IRR", "online", "2028-01-05", "confirmed", "SMOKE-2028-DON-101", "2028-01-04T10:00:00", None),
        (TEST_ID_BASE + 102, TEST_ID_BASE + 2, TEST_ID_BASE + 1, Decimal("2000.00"), "IRR", "bank_transfer", "2028-02-10", "confirmed", "SMOKE-2028-DON-102", "2028-02-09T10:00:00", None),
        (TEST_ID_BASE + 103, TEST_ID_BASE + 1, TEST_ID_BASE + 1, Decimal("500.00"), "IRR", "cash", "2028-02-20", "pending", "SMOKE-2028-DON-103", "2028-02-20T10:00:00", None),
    ]
    insert_with_identity(conn, f"{SOURCE_DB}.finance_ops.donations", donation_cols, donations)

    expense_cols = ["id", "center_id", "child_id", "category_id", "amount", "currency", "expense_date", "description", "approved_by_user_id", "status", "created_at", "updated_at"]
    expenses = [
        (TEST_ID_BASE + 201, 1, 1, TEST_ID_BASE + 2, Decimal("100.00"), "IRR", "2028-01-15", "Smoke January approved expense.", 10, "approved", "2028-01-15T11:00:00", None),
        (TEST_ID_BASE + 202, 1, 2, TEST_ID_BASE + 3, Decimal("250.00"), "IRR", "2028-02-18", "Smoke February approved expense.", 10, "approved", "2028-02-18T11:00:00", None),
    ]
    insert_with_identity(conn, f"{SOURCE_DB}.finance_ops.expenses", expense_cols, expenses)

    payment_cols = ["id", "payment_type", "teacher_id", "center_id", "amount", "currency", "payment_date", "status", "created_at", "updated_at"]
    payments = [
        (TEST_ID_BASE + 301, "salary", 1001, 1, Decimal("300.00"), "IRR", "2028-01-25", "paid", "2028-01-25T12:00:00", None),
        (TEST_ID_BASE + 302, "vendor", None, 1, Decimal("400.00"), "IRR", "2028-02-26", "paid", "2028-02-26T12:00:00", None),
    ]
    insert_with_identity(conn, f"{SOURCE_DB}.finance_ops.payments", payment_cols, payments)

    allocation_cols = ["id", "source_type", "source_id", "center_id", "child_id", "category_id", "allocated_amount", "allocation_date", "reason", "created_at"]
    allocations = [
        (TEST_ID_BASE + 401, "donation", TEST_ID_BASE + 101, 1, 1, TEST_ID_BASE + 2, Decimal("700.00"), "2028-01-06", "Smoke allocation: Jan donor A to center 1.", "2028-01-06T13:00:00"),
        (TEST_ID_BASE + 402, "donation", TEST_ID_BASE + 101, 2, None, TEST_ID_BASE + 3, Decimal("300.00"), "2028-01-07", "Smoke allocation: Jan donor A to center 2.", "2028-01-07T13:00:00"),
        (TEST_ID_BASE + 403, "donation", TEST_ID_BASE + 102, 1, 2, TEST_ID_BASE + 2, Decimal("1200.00"), "2028-02-11", "Smoke allocation: Feb confirmed donor B to center 1.", "2028-02-11T13:00:00"),
        (TEST_ID_BASE + 404, "donation", TEST_ID_BASE + 103, 1, 1, TEST_ID_BASE + 2, Decimal("200.00"), "2028-02-22", "Smoke allocation: Feb pending donation should not count as donation amount.", "2028-02-22T13:00:00"),
    ]
    insert_with_identity(conn, f"{SOURCE_DB}.finance_ops.budget_allocations", allocation_cols, allocations)

    tx_cols = ["id", "entity_type", "entity_id", "transaction_type", "amount", "transaction_date", "created_at"]
    tx_rows = [
        (TEST_ID_BASE + 501, "donation", TEST_ID_BASE + 101, "credit", Decimal("1000.00"), "2028-01-05", "2028-01-05T14:00:00"),
        (TEST_ID_BASE + 502, "expense", TEST_ID_BASE + 201, "debit", Decimal("100.00"), "2028-01-15", "2028-01-15T14:00:00"),
        (TEST_ID_BASE + 503, "payment", TEST_ID_BASE + 301, "debit", Decimal("300.00"), "2028-01-25", "2028-01-25T14:00:00"),
    ]
    insert_with_identity(conn, f"{SOURCE_DB}.finance_ops.financial_transactions", tx_cols, tx_rows)

    rate_cols = ["id", "from_currency", "to_currency", "rate", "rate_date"]
    rates = [
        (TEST_ID_BASE + 601, "USD", "IRR", Decimal("500000.00000000"), "2028-01-01"),
        (TEST_ID_BASE + 602, "EUR", "IRR", Decimal("550000.00000000"), "2028-01-01"),
    ]
    insert_with_identity(conn, f"{SOURCE_DB}.finance_ops.currency_rates", rate_cols, rates)

    conn.commit()


def apply_incremental_source_changes(conn: pyodbc.Connection) -> None:
    print("Applying deterministic INCREMENTAL source changes for March 2028...")

    # SCD Type 1 dimension update checks.
    exec_sql(
        conn,
        f"""
        UPDATE {SOURCE_DB}.finance_ops.donors
           SET full_name = N'Smoke 2028 Donor A - Updated', updated_at = '2028-03-15T08:00:00'
         WHERE id = ?;
        """,
        [TEST_ID_BASE + 1],
    )
    exec_sql(
        conn,
        f"""
        UPDATE {SOURCE_DB}.finance_ops.campaigns
           SET title = N'Smoke 2028 Campaign - Updated', status = N'closed', updated_at = '2028-03-15T08:00:00'
         WHERE id = ?;
        """,
        [TEST_ID_BASE + 1],
    )
    exec_sql(
        conn,
        f"""
        UPDATE {SOURCE_DB}.finance_ops.expense_categories
           SET name = N'Smoke Books - Updated', updated_at = '2028-03-15T08:00:00'
         WHERE id = ?;
        """,
        [TEST_ID_BASE + 2],
    )

    donation_cols = ["id", "donor_id", "campaign_id", "amount", "currency", "donation_type", "donation_date", "status", "reference_code", "created_at", "updated_at"]
    donations = [
        (TEST_ID_BASE + 104, TEST_ID_BASE + 1, TEST_ID_BASE + 1, Decimal("1500.00"), "IRR", "online", "2028-03-10", "confirmed", "SMOKE-2028-DON-104", "2028-03-10T10:00:00", None),
    ]
    insert_with_identity(conn, f"{SOURCE_DB}.finance_ops.donations", donation_cols, donations)

    expense_cols = ["id", "center_id", "child_id", "category_id", "amount", "currency", "expense_date", "description", "approved_by_user_id", "status", "created_at", "updated_at"]
    expenses = [
        (TEST_ID_BASE + 203, 1, 1, TEST_ID_BASE + 2, Decimal("200.00"), "IRR", "2028-03-12", "Smoke March approved expense.", 10, "approved", "2028-03-12T11:00:00", None),
    ]
    insert_with_identity(conn, f"{SOURCE_DB}.finance_ops.expenses", expense_cols, expenses)

    payment_cols = ["id", "payment_type", "teacher_id", "center_id", "amount", "currency", "payment_date", "status", "created_at", "updated_at"]
    payments = [
        (TEST_ID_BASE + 303, "bonus", 1002, 1, Decimal("100.00"), "IRR", "2028-03-20", "paid", "2028-03-20T12:00:00", None),
    ]
    insert_with_identity(conn, f"{SOURCE_DB}.finance_ops.payments", payment_cols, payments)

    allocation_cols = ["id", "source_type", "source_id", "center_id", "child_id", "category_id", "allocated_amount", "allocation_date", "reason", "created_at"]
    allocations = [
        (TEST_ID_BASE + 405, "donation", TEST_ID_BASE + 104, 1, 1, TEST_ID_BASE + 2, Decimal("1000.00"), "2028-03-11", "Smoke allocation: March confirmed donation to center 1.", "2028-03-11T13:00:00"),
    ]
    insert_with_identity(conn, f"{SOURCE_DB}.finance_ops.budget_allocations", allocation_cols, allocations)

    tx_cols = ["id", "entity_type", "entity_id", "transaction_type", "amount", "transaction_date", "created_at"]
    tx_rows = [
        (TEST_ID_BASE + 504, "donation", TEST_ID_BASE + 104, "credit", Decimal("1500.00"), "2028-03-10", "2028-03-10T14:00:00"),
        (TEST_ID_BASE + 505, "expense", TEST_ID_BASE + 203, "debit", Decimal("200.00"), "2028-03-12", "2028-03-12T14:00:00"),
        (TEST_ID_BASE + 506, "payment", TEST_ID_BASE + 303, "debit", Decimal("100.00"), "2028-03-20", "2028-03-20T14:00:00"),
    ]
    insert_with_identity(conn, f"{SOURCE_DB}.finance_ops.financial_transactions", tx_cols, tx_rows)

    conn.commit()


# =============================================================================
# ETL runners
# =============================================================================


def run_source_to_staging(conn: pyodbc.Connection, to_date: str) -> None:
    print(f"Running Source -> Staging ETL to_date={to_date}...")
    exec_sql(conn, f"EXEC {STG_DB}.etl_admin.usp_run_stg_finance_ops_all @to_date = ?;", [to_date])
    conn.commit()


def run_dw_first_load(conn: pyodbc.Connection) -> None:
    print("Running DW first-load ETL for Jan/Feb 2028...")
    exec_sql(
        conn,
        f"""
        EXEC {DW_DB}.etl_admin.usp_first_load_dw_finance_mart2_all
             @start_time = ?,
             @end_time = ?,
             @run_staging = 0;
        """,
        [FIRST_LOAD_START, FIRST_LOAD_END],
    )
    conn.commit()


def run_dw_incremental(conn: pyodbc.Connection) -> None:
    print("Running DW normal/incremental ETL for Mar 2028...")
    exec_sql(
        conn,
        f"""
        EXEC {DW_DB}.etl_admin.usp_load_dw_finance_mart2_daily
             @start_time = ?,
             @end_time = ?,
             @run_staging = 0;
        """,
        [INCREMENTAL_START, INCREMENTAL_END],
    )
    conn.commit()


# =============================================================================
# Verification helpers
# =============================================================================


def dec(value: Any) -> Decimal:
    if value is None:
        return Decimal("0.00")
    return Decimal(str(value)).quantize(Decimal("0.01"))


def get_center_key(conn: pyodbc.Connection, center_id: int) -> int:
    val = scalar(conn, f"SELECT TOP (1) center_key FROM {DW_DB}.dw.dim_center WHERE center_id = ?", [center_id])
    return int(val) if val is not None else -1


def snapshot_row(conn: pyodbc.Connection, month_key: int, center_key: int) -> pyodbc.Row | None:
    return fetch_one(
        conn,
        f"""
        SELECT month_key, center_key, total_donation_amount, total_expense_amount, total_payment_amount,
               net_balance, donation_count, expense_count, payment_count, allocation_count
        FROM {DW_DB}.dw.fact_monthly_financial_snapshot
        WHERE month_key = ? AND center_key = ?;
        """,
        [month_key, center_key],
    )


def verify_snapshot(
    conn: pyodbc.Connection,
    results: list[tuple[str, bool, str]],
    label: str,
    month_key: int,
    center_key: int,
    expected: dict[str, Any],
) -> None:
    row = snapshot_row(conn, month_key, center_key)
    if row is None:
        assert_or_record(results, label, False, f"missing snapshot row month_key={month_key}, center_key={center_key}")
        return

    checks = {
        "total_donation_amount": dec(row.total_donation_amount) == dec(expected["total_donation_amount"]),
        "total_expense_amount": dec(row.total_expense_amount) == dec(expected["total_expense_amount"]),
        "total_payment_amount": dec(row.total_payment_amount) == dec(expected["total_payment_amount"]),
        "net_balance": dec(row.net_balance) == dec(expected["net_balance"]),
        "donation_count": int(row.donation_count or 0) == int(expected["donation_count"]),
        "expense_count": int(row.expense_count or 0) == int(expected["expense_count"]),
        "payment_count": int(row.payment_count or 0) == int(expected["payment_count"]),
        "allocation_count": int(row.allocation_count or 0) == int(expected["allocation_count"]),
    }
    ok = all(checks.values())
    detail = "actual=(don={0}, exp={1}, pay={2}, net={3}, dc={4}, ec={5}, pc={6}, ac={7})".format(
        row.total_donation_amount,
        row.total_expense_amount,
        row.total_payment_amount,
        row.net_balance,
        row.donation_count,
        row.expense_count,
        row.payment_count,
        row.allocation_count,
    )
    if not ok:
        failed = [k for k, v in checks.items() if not v]
        detail += f" failed={failed} expected={expected}"
    assert_or_record(results, label, ok, detail)


def verify_staging_validity(conn: pyodbc.Connection, results: list[tuple[str, bool, str]]) -> None:
    tables = ["donors", "campaigns", "expense_categories", "donations", "expenses", "payments", "budget_allocations", "financial_transactions", "currency_rates"]
    for tbl in tables:
        id_col = "id"
        cnt_invalid = scalar(
            conn,
            f"""
            SELECT COUNT(1)
            FROM {STG_DB}.stg_finance_ops.{tbl}
            WHERE {id_col} >= ? AND ISNULL(is_valid, 0) <> 1;
            """,
            [TEST_ID_BASE],
        )
        assert_or_record(results, f"staging valid rows: {tbl}", int(cnt_invalid or 0) == 0, f"invalid_count={cnt_invalid}")


def verify_first_load(conn: pyodbc.Connection) -> list[tuple[str, bool, str]]:
    print("\nVerifying FIRST-LOAD result...")
    results: list[tuple[str, bool, str]] = []

    verify_staging_validity(conn, results)

    # Dimension existence.
    donor_count = scalar(conn, f"SELECT COUNT(1) FROM {DW_DB}.dw.dim_donor WHERE donor_id IN (?, ?)", [TEST_ID_BASE + 1, TEST_ID_BASE + 2])
    assert_or_record(results, "dim_donor first-load inserted 2 test donors", int(donor_count or 0) == 2, f"count={donor_count}")

    campaign_count = scalar(conn, f"SELECT COUNT(1) FROM {DW_DB}.dw.dim_campaign WHERE campaign_id = ?", [TEST_ID_BASE + 1])
    assert_or_record(results, "dim_campaign first-load inserted test campaign", int(campaign_count or 0) == 1, f"count={campaign_count}")

    category_count = scalar(conn, f"SELECT COUNT(1) FROM {DW_DB}.dw.dim_category WHERE category_id IN (?, ?, ?)", [TEST_ID_BASE + 1, TEST_ID_BASE + 2, TEST_ID_BASE + 3])
    assert_or_record(results, "dim_category first-load inserted 3 test categories", int(category_count or 0) == 3, f"count={category_count}")

    # Fact existence.
    fact_checks = [
        ("fact_donation_transaction first-load count", "fact_donation_transaction", "source_donation_id", 3),
        ("fact_expense_transaction first-load count", "fact_expense_transaction", "source_expense_id", 2),
        ("fact_payment_transaction first-load count", "fact_payment_transaction", "source_payment_id", 2),
        ("fact_budget_allocation_event first-load count", "fact_budget_allocation_event", "source_allocation_id", 4),
        ("fact_donation_lifecycle first-load count", "fact_donation_lifecycle", "source_donation_id", 3),
    ]
    for label, table, source_col, expected_count in fact_checks:
        cnt = scalar(conn, f"SELECT COUNT(1) FROM {DW_DB}.dw.{table} WHERE {source_col} >= ? AND {source_col} < ?", [TEST_ID_BASE, TEST_ID_BASE + 1000])
        assert_or_record(results, label, int(cnt or 0) == expected_count, f"count={cnt}, expected={expected_count}")

    # Date keys should not be -1 for transaction/event facts.
    for table, source_col in [
        ("fact_donation_transaction", "source_donation_id"),
        ("fact_expense_transaction", "source_expense_id"),
        ("fact_payment_transaction", "source_payment_id"),
        ("fact_budget_allocation_event", "source_allocation_id"),
    ]:
        bad = scalar(conn, f"SELECT COUNT(1) FROM {DW_DB}.dw.{table} WHERE {source_col} >= ? AND date_key = -1", [TEST_ID_BASE])
        assert_or_record(results, f"{table} no test date_key = -1", int(bad or 0) == 0, f"bad_count={bad}")

    center1 = get_center_key(conn, 1)
    center2 = get_center_key(conn, 2)
    assert_or_record(results, "center 1 resolves to real center_key", center1 != -1, f"center_key={center1}")
    assert_or_record(results, "center 2 resolves to real center_key", center2 != -1, f"center_key={center2}")

    verify_snapshot(
        conn,
        results,
        "snapshot Jan 2028 center 1",
        20280131,
        center1,
        {
            "total_donation_amount": "700.00",
            "total_expense_amount": "100.00",
            "total_payment_amount": "300.00",
            "net_balance": "300.00",
            "donation_count": 1,
            "expense_count": 1,
            "payment_count": 1,
            "allocation_count": 1,
        },
    )
    verify_snapshot(
        conn,
        results,
        "snapshot Jan 2028 center 2",
        20280131,
        center2,
        {
            "total_donation_amount": "300.00",
            "total_expense_amount": "0.00",
            "total_payment_amount": "0.00",
            "net_balance": "300.00",
            "donation_count": 1,
            "expense_count": 0,
            "payment_count": 0,
            "allocation_count": 1,
        },
    )
    verify_snapshot(
        conn,
        results,
        "snapshot Feb 2028 center 1",
        20280229,
        center1,
        {
            "total_donation_amount": "1200.00",
            "total_expense_amount": "250.00",
            "total_payment_amount": "400.00",
            "net_balance": "550.00",
            "donation_count": 1,
            "expense_count": 1,
            "payment_count": 1,
            "allocation_count": 2,
        },
    )

    return results


def verify_incremental(conn: pyodbc.Connection) -> list[tuple[str, bool, str]]:
    print("\nVerifying INCREMENTAL result...")
    results: list[tuple[str, bool, str]] = []

    # SCD Type 1 dimension updates.
    donor_name = scalar(conn, f"SELECT full_name FROM {DW_DB}.dw.dim_donor WHERE donor_id = ?", [TEST_ID_BASE + 1])
    assert_or_record(results, "dim_donor SCD1 updated donor name", donor_name == "Smoke 2028 Donor A - Updated", f"full_name={donor_name}")

    campaign = fetch_one(conn, f"SELECT title, campaign_status FROM {DW_DB}.dw.dim_campaign WHERE campaign_id = ?", [TEST_ID_BASE + 1])
    campaign_ok = campaign is not None and campaign.title == "Smoke 2028 Campaign - Updated" and campaign.campaign_status == "closed"
    assert_or_record(results, "dim_campaign SCD1 updated title/status", campaign_ok, f"actual={tuple(campaign) if campaign else None}")

    category_name = scalar(conn, f"SELECT category_name FROM {DW_DB}.dw.dim_category WHERE category_id = ?", [TEST_ID_BASE + 2])
    assert_or_record(results, "dim_category SCD1 updated category name", category_name == "Smoke Books - Updated", f"category_name={category_name}")

    # March facts inserted.
    fact_checks = [
        ("fact_donation_transaction incremental inserted D104", "fact_donation_transaction", "source_donation_id", TEST_ID_BASE + 104),
        ("fact_expense_transaction incremental inserted E203", "fact_expense_transaction", "source_expense_id", TEST_ID_BASE + 203),
        ("fact_payment_transaction incremental inserted P303", "fact_payment_transaction", "source_payment_id", TEST_ID_BASE + 303),
        ("fact_budget_allocation_event incremental inserted A405", "fact_budget_allocation_event", "source_allocation_id", TEST_ID_BASE + 405),
        ("fact_donation_lifecycle incremental inserted D104", "fact_donation_lifecycle", "source_donation_id", TEST_ID_BASE + 104),
    ]
    for label, table, col, val in fact_checks:
        cnt = scalar(conn, f"SELECT COUNT(1) FROM {DW_DB}.dw.{table} WHERE {col} = ?", [val])
        assert_or_record(results, label, int(cnt or 0) == 1, f"count={cnt}")

    center1 = get_center_key(conn, 1)
    verify_snapshot(
        conn,
        results,
        "snapshot Mar 2028 center 1",
        20280331,
        center1,
        {
            "total_donation_amount": "1000.00",
            "total_expense_amount": "200.00",
            "total_payment_amount": "100.00",
            "net_balance": "700.00",
            "donation_count": 1,
            "expense_count": 1,
            "payment_count": 1,
            "allocation_count": 1,
        },
    )

    # Idempotency: no duplicate rows for core March facts after one run.
    duplicate_checks = [
        ("donation D104 no duplicate", "fact_donation_transaction", "source_donation_id", TEST_ID_BASE + 104),
        ("expense E203 no duplicate", "fact_expense_transaction", "source_expense_id", TEST_ID_BASE + 203),
        ("payment P303 no duplicate", "fact_payment_transaction", "source_payment_id", TEST_ID_BASE + 303),
        ("allocation A405 no duplicate", "fact_budget_allocation_event", "source_allocation_id", TEST_ID_BASE + 405),
    ]
    for label, table, col, val in duplicate_checks:
        cnt = scalar(conn, f"SELECT COUNT(1) FROM {DW_DB}.dw.{table} WHERE {col} = ?", [val])
        assert_or_record(results, label, int(cnt or 0) == 1, f"count={cnt}")

    return results


def print_summary(all_results: list[tuple[str, bool, str]]) -> None:
    total = len(all_results)
    failed = [r for r in all_results if not r[1]]
    print("\n" + "=" * 80)
    print(f"SMOKE TEST SUMMARY: {total - len(failed)}/{total} passed")
    if failed:
        print("FAILED CHECKS:")
        for name, _, detail in failed:
            print(f"  - {name}: {detail}")
        sys.exit(1)
    print("All checks passed.")


# =============================================================================
# Main flow
# =============================================================================


def main() -> None:
    print("Finance MART 2 2028 end-to-end smoke test")
    print("Server:", SERVER)
    print("Test ID base:", TEST_ID_BASE)

    conn = connect()
    try:
        if CLEAN_PREVIOUS_TEST_ROWS:
            clean_previous_test_rows(conn)

        ensure_conformed_dims(conn)

        insert_first_load_source_data(conn)
        run_source_to_staging(conn, FIRST_LOAD_END)
        run_dw_first_load(conn)
        first_results = verify_first_load(conn)

        apply_incremental_source_changes(conn)
        run_source_to_staging(conn, INCREMENTAL_END)
        run_dw_incremental(conn)
        incremental_results = verify_incremental(conn)

        print_summary(first_results + incremental_results)

    except Exception:
        conn.rollback()
        print("\nERROR: Smoke test failed before completion.")
        raise
    finally:
        conn.close()


if __name__ == "__main__":
    main()
